esphome:
  name: livingroom

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "tesseract"
  password: "Tessmo67"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Fallback Hotspot"
    password: "PHm5OlcEoPOr"

captive_portal:

i2c:
  sda: D2
  scl: D1
  frequency: 800kHz

font:
  - id: hack
    file: "Hack-Regular.ttf"
    size: 15 
  - id: hack10
    file: "Hack-Regular.ttf"
    size: 10 

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 1s
    lambda: |-
      it.print(0, 0, id(hack), "Hello World!");

external_components:
  - source:
        type: local
        path: ./components

wiegand_reader:
  - id: reader
    d0: D6
    d1: D5
    on_tag:
      - lambda: |-
          ESP_LOGD("reader", "Read tag %s", x.c_str());
    